execute_process(COMMAND git describe --all
	OUTPUT_VARIABLE RELEASE
	OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND whoami
	OUTPUT_VARIABLE WHOAMI
	OUTPUT_STRIP_TRAILING_WHITESPACE)
execute_process(COMMAND date
	OUTPUT_VARIABLE DATE
	OUTPUT_STRIP_TRAILING_WHITESPACE)

configure_file(${CMAKE_CURRENT_LIST_DIR}/version.h.in ${CMAKE_CURRENT_LIST_DIR}/version.h)

