# THIS IS NOT A STAND-ALONE MAKEFILE.
#
# It is designed to be included by the main UglyCODE Makefile in ../..
#
# PJC, 20/4/2003.

OS_RAW_LIB_OBJECTS:= \
	crypt3.o \
	getopt.o \
	getopt1.o \
	_rand48.o \
	lrand48.o \
	srand48.o

$(BUILD_DIR)/crypt3.o: $(CONFIG_DIR)/src/crypt3.c

$(BUILD_DIR)/getopt.o: $(CONFIG_DIR)/src/getopt.c

$(BUILD_DIR)/getopt1.o: $(CONFIG_DIR)/src/getopt1.c

$(BUILD_DIR)/_rand48.o: $(CONFIG_DIR)/src/_rand48.c

$(BUILD_DIR)/lrand48.o: $(CONFIG_DIR)/src/lrand48.c

$(BUILD_DIR)/srand48.o: $(CONFIG_DIR)/src/srand48.c
